version: "3.7"

services:

  app:
    container_name: app-container
    build:
      context: ./
      dockerfile: Dockerfile  
    restart: unless-stopped  
    volumes:
      - ./site:/var/www/html 
    working_dir: &app-dir /var/www/html
    networks:
      - app-network 

  caddy:
    image: caddy:alpine
    container_name: caddy-container
    restart: unless-stopped
    ports:
      - "80:80"
      - "444:443"
      - "444:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/var/www/html
      - $PWD/data/caddy_data:/data
      - $PWD/data/caddy_config:/config
    networks:
      - app-network
  


  db:
    image: mysql
    container_name: db-container
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vifa                       
    volumes:
      - vifa-mysql-data:/var/lib/mysql 
    networks:
      - app-network

networks:
  app-network:

volumes:
  vifa-mysql-data: